var museumInfo = {
headInfo: [
    
    {infoCap: 'Vatnajokull: Iceland', class: 'infoCaption', name:'iceland',},
    {infoCap: 'Grand Canyon National Park: Arizona, USA', class: 'infoCaption', name:'arizona',},
    {infoCap: 'Moravian Fields: Czech Republic', class: 'infoCap:tion', name:'czech',},
    {infoCap: 'Ashikaga Flower Park: Ashikaga, Japan', class: 'infoCap:tion', name:'ashikaga',},
    {infoCap: 'Oia: Santorini, Greece', class: 'infoCaption', name:'greece',},
    {infoCap: 'Arashiyama: Kyoto, Japan', class: 'infoCaption', name:'japan',},
    {infoCap: 'Bagan (formerly Pagan): Myanmar', class: 'infoCaption', name:'myanmar',},
    {infoCap: 'Namaqualand: South Africa', class: 'infoCaption', name:'namaqualand',},
    {infoCap: 'Namib Desert: Namibia', class: 'infoCaption', name:'namibia',},
    {infoCap: 'Halong Bay: Vietnam', class: 'infoCaption', name:'bay-vietnam',},
    {infoCap: 'Glowworm Caves: Waitomo, New Zealand', class: 'infoCaption', name:'waitomo',},
    {infoCap: 'Fernando de Noronha: Brazil', class: 'infoCaption', name:'noronha',},
    {infoCap: 'Bryce Canyon: Bryce, Utah', class: 'infoCaption', name:'utah',},
    {infoCap: 'Mu Cang Chai: Vietnam', class: 'infoCaption', name:'vietnam',},
    {infoCap: 'Wulingyuan Scenic Area: Zhangjiajie, China', class: 'infoCaption', name:'zhangjiajie',}, 
    {infoCap: 'Lavender fields: Provence, France', class: 'infoCaption', name:'france',}
],
description: [
    
    
    {info: 'Vatnajokull, also known as the Water Glacier in English, is the largest and most voluminous ice cap in Iceland, and one of the largest in area in Europe. It is the second largest glacier in area after Austfonna on Svalbard in Norway but, nevertheless, larger by volume. It is located in the south-east of the island, covering more than 8 percent of the country. The name Vatnajokull is derived from vatna, the genitive plural form of vatn which means "water" in Icelandic but is also used to refer to a lake, and jokull, the Icelandic for glacier. Vatnajokull has around 30 outlet glaciers flowing from the ice cap. The Icelandic term for glacier is jokull, and so is the term for outlet glacier.', class: 'bigInfo', name: 'iceland'},
    
    {info: 'The Grand Canyon is a steep-snameed canyon carved by the Colorado River in Arizona. The canyon and adjacent rim are contained within Grand Canyon National Park, the Kaibab National Forest, Grand Canyon-Parashant National Monument, the Hualapai Indian Reservation, the Havasupai Indian Reservation and the Navajo Nation. Presnameent Theodore Roosevelt was a major proponent of preservation of the Grand Canyon area, and visited it on numerous occasions to hunt and enjoy the scenery. Nearly two billion years of Earths geological history have been exposed as the Colorado River and its tributaries cut their channels through layer after layer of rock while the Colorado Plateau was uplifted.', class: 'bigInfo', name: 'arizona'},
    
    {info: 'Moravia is a historical country in the Czech Republic and one of the historical Czech lands, together with Bohemia and Czech Silesia. The medieval and early modern Margraviate of Moravia was a crown land of the Lands of the Bohemian Crown, an imperial state of the Holy Roman Empire, later a crown land of the Austrian Empire and briefly also one of 17 former crown lands of the Cisleithanian part of the Austro-Hungarian Empire from 1867 to 1918. During the early 20th century, Moravia was one of the five lands of Czechoslovakia from 1918 to 1928; it was then merged with Czech Silesia, and eventually dissolved by abolition of the land system in 1949.', class: 'bigInfo', name: 'czech'},
    
    {info: 'The Japanese love flowers, and wisteria are among their favorites. Wisteria are called fuji in Japanese, like Mt. Fuji, but unlike the mountain, the flower is pronounced by stressing the second syllable. One of the best places to view fuji flowers is the Ashikaga Flower Park in Ashikaga City, Tochigi Prefecture. Ashikaga Flower Park features lots of blue, white and pink fuji, as well as yellow laburnum (Japanese: kingusari) that look like yellow colored fuji. One large fuji tree is 100 years old and its branches are supported to create a huge umbrella of blue fuji flowers. There is also a long tunnel of white fuji flowers, while a tunnel of yellow kingusari needs a few more years to become an actual tunnel.', class: 'bigInfo', name: 'ashikaga'},
    
    {info: 'Oia is a small village and former community in the South Aegean on the islands of Thira and Therasia, in the Cyclades, Greece. The local government reform it has been part of the municipality of Santorini, of which it is a municipal unit. It covers the whole island of Therasia and the northwesternmost part of Santorini, which it shares with the municipal unit of Santorini. Main street is named Nikolaou Nomikou. The population was 1545 inhabitants at the 2011 census, and the land area is 19449 km. Oia was previously known as Apano Meria, a name which still occurs locally as Pano Meria, and the inhabitants are still called Apanomerites.The Ancient Greek Oia was one of two harbours of ancient Thera and was located in the southeast of the island, where Kamari is now.', class: 'bigInfo', name: 'greece'},
    
    {info: 'Arashiyama is a district on the western outskirts of Kyoto, Japan. Arashiyama is a nationally designated Historic Site and Place of Scenic Beauty. Arashiyama Bamboo GroveThe Iwatayama Monkey Park on the slopes of Arashiyama. Over 170 monkeys live at the park. While the monkeys are wild, they have become accustomed to humans. The park is on a small mountain not far from the Saga-Arashiyama rail station. Visitors can approach and photograph the monkeys. At the summit is a fenced enclosure where visitors can feed the monkeys.The "Moon Crossing Brnamege notable for its views of cherry blossoms and autumn colors on the slopes of Arashiyama.The tombstone of the Heike courtesan Kogo of Sagano.', class: 'bigInfo', name: 'japan'},
    
     {info: 'Bagan is an ancient city located in the Mandalay Region of Myanmar. From the 9th to 13th centuries, the city was the capital of the Pagan Kingdom, the first kingdom that unified the regions that would later constitute modern Myanmar. During the kingdoms height between the 11th and 13th centuries, over 10,000 Buddhist temples, pagodas and monasteries were constructed in the Bagan plains alone, of which the remains of over 2,200 temples and pagodas still survive to the present day. The Bagan Archaeological Zone is a main attraction for the countrys nascent tourism industry. It is seen by many as equal in attraction to Angkor Wat in Cambodia.According to the Burmese chronicles, Bagan was founded in the second century AD, and fortified in 849.', class: 'bigInfo', name: 'myanmar'},
    
    {info: 'Namaqualand is an arname region of Namibia, extending along the west coast over 1,000 kilometres and covering a total area of 440,000 square kilometres. It is divnameed by the lower course of the Orange River into two portions – Little Namaqualand to the south and Great Namaqualand to the north.Little Namaqualand is within the Namakwa District Municipality, forming part of Northern Cape Province, South Africa. It is geographically the largest district in the country, spanning over 26836 km.A typical municipality is Kamiesberg Local Municipality. The semi-desert Succulent Karoo region experiences hot summers, sparse rainfall and cold winters. Great Namaqualand is in the Karas Region of Namibia.', class: 'bigInfo', name: 'namaqualand'},
    
    {info: 'The Namib is a coastal desert in southern Africa. The name Namib is of Nama origin and means vast place. According to the broadest definition, the Namib stretches for more than 2,000 km along the Atlantic coasts of Angola, Namibia, and South Africa, extending southward from the Carunjamba River in Angola, through Namibia and to the Olifants River in Western Cape, South Africa. The Namibs northernmost portion, which extends 450 kilometres from the Angola-Namibia border, is known as Moçâmedes Desert, while its southern portion approaches the neighboring Kalahari Desert. From the Atlantic coast eastward, the Namib gradually ascends in elevation, reaching up to 200 kilometres inland to the foot of the Great Escarpment. Annual precipitation ranges from 2 millimetres in the most arname regions to 200 millimetres at the escarpment, making the Namib the only true desert in southern Africa.', class: 'bigInfo', name: 'namibia'},
    
    {info: 'Ha Long Bay is a UNESCO World Heritage Site in Quang Ninh Province. Administratively, the bay belongs to Ha Long City, Cam Pha town, and is a part of Van Don District. The bay features thousands of limestone karsts and isles in various shapes and sizes. Ha Long Bay is a center of a larger zone which includes Bai Tu Long Bay to the northeast, and Cat Ba Island to the southwest. These larger zones share a similar geological, geographical, geomorphological, climate, and cultural characters. The core of the bay has an area of 334 km with a high density of 775 islets.The limestone in this bay has gone through 500 mil years of formation in different conditions and environments. The evolution of the karst in this bay has taken 20m. years under the impact of the tropical wet climate.', class: 'bigInfo', name: 'bay-vietnam'},
    
    {info: 'The Bryce Canyon area was settled by Mormon pioneers in the 1850s and was named after Ebenezer Bryce, who homesteaded in the area in 1874. The area around Bryce Canyon was originally designated as a national monument by Presnameent Warren G. Harding in 1923 and was redesignated as a national park by Congress in 1928. The park covers 35,835 acres and receives substantially fewer visitors than Zion National Park (nearly 4.3 million in 2016) or Grand Canyon National Park (nearly 6 million in 2016), largely due to Bryces more remote location. In 2016, Bryce Canyon received 2,365,110 recreational visitors, representing an increase of 35% from the prior year.', class: 'bigInfo', name: 'waitomo'},
    
    {info: 'Mu Cang Chai is a rural district of Yen Bai Province, in the Northwest region of Vietnam. As of 2003, the district had a population of 42,574. The district covers an area of 1,199 km². The district capital lies at Mu Cang Chai. Mu Cang Chải is a district of Yen Bai province. It shares the border in the north with Van Ban district of Lao Cai province, neighboring in the south of Muong La district of Son La province, being the west of Than Uyen Lai Chau province, sharing in the east of Van Chan district and Yen Bai province. The district is located at the foot of Hoang Lien Son mountain range, at an altitude of 1,000 metres above sea level. To get to Mu Cang Chai district, travellers must pass through Khau Phạ Pass, which is one of four imposing passes in the northwest of Vietnam.', class: 'bigInfo', name: 'noronha'},
    
    {info: 'Glow worms in the Waitomo Caves The Waitomo Glowworm Caves attraction is a cave at Waitomo on the North Island of New Zealand. It is known for its population of Arachnocampa luminosa, a glowworm species found exclusively in New Zealand. This cave is part of the Waitomo Caves system that includes the Ruakuri Cave and the Aranui Cave. The attraction has a modern visitor centre at the entrance, largely designed in wood. There are organized tours that include a boat rnamee under the glowworms. The name "Waitomo" comes from the Maori words wai, water and tomo, hole or shaft. The local Maori people had known about the caves for about a century before a local Maori, Laurence Cussen and Fred Mace, were shown the entrance in 1884.', class: 'bigInfo', name: 'utah'},  
    
    {info: 'The historical province of Provence within the modern region of ProvenceAlpesCote dAzur in southeast France.Provence is a geographical region and historical province of southeastern France, which extends from the left bank of the lower Rone River to the west to the Italian border to the east, and is bordered by the Mediterranean Sea to the south. It largely corresponds with the modern administrative region of Bouchesdu, and parts of Maritimes. The largest city of the region is Marseille. The Romans made the region into the first Roman province beyond the Alps and called it Provincia Romana, which evolved into the present name. It was ruled by the Counts of Provence from their capital in AixenProvence until 1481, when it became a province of France.', class: 'bigInfo', name: 'vietnam'},
    
    {info: 'Wulingyuan is a historical site in southcentral Chinas. It is noted for more than 3,000 quartzite sandstone pillars and peaks across most of the site along with many ravines and gorges with attractive streams, pools, lakes, rivers and waterfalls. It features 40 caves, many with large calcite deposits, and two natural brnameges, Xianrenqiao and Tianqiashengkong. The site is situated between in the Zhangjiajie City and lies about 270 kilometres to the northwest of Changsha, the capital of Hunan Province. The park covers an area of 690 square kilometers.Wulingyuan forms part of the Wuling Mountain Range. The scenic area consists of national parks, which are the Zhangjiajie National Forest Park, Suoxi Valley Nature Reserve...', class: 'bigInfo', name: 'zhangjiajie'},
    
    {info: 'Fernando de Noronha is an archipelago of 21 islands and islets in the Atlantic Ocean, 354 km offshore from the Brazilian coast. The archipelagos name is a corruption of the name of the Portuguese merchant Fernão de Loronha, to whom it was given by the Portuguese crown for services rendered regarding wood imported from Brazil. Only the homonymous main island is inhabited; it has an area of 18.4 km and a population estimated at 2,718. The archipelagos total area is 26 km. Administratively, the islands are a unique case in Brazil of a special "state district" that is not part of any municipality and is administered directly by the government of the state of Pernambuco. The state districts jurisdiction also includes the very remote Saint Paul Archipelago.', class: 'bigInfo', name: 'france'}
]
}